version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build-and-deploy:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - node/install
      - aws-cli/install
      - run:
          name: Install Frontend
          command: npm run frontend:install
      - run:
          name: Build Frontend
          command: npm run frontend:build
      - run:
          name: Deploy Frontend
          command: npm run frontend:deploy
      - run:
          name: Back-End Install
          command: npm run api:install
      - run:
          name: Build and Archive Backend
          command: |-
            printenv > www/.env
            npm run archive
      - run:
          name: Deploy Backend
          command: |-
            aws s3 cp ./www/Archive.zip $S3_BUCKET_SERVER
            aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_ENV --version-label <<pipeline.git.revision>>
workflows:
  test-env-vars:
    jobs:
      - build-and-deploy:
        context: AWS