version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
workflows:
  test-env-vars:
    jobs:
      - build-and-deploy
jobs:
  build-and-deploy:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - node/install
      - aws-cli/install
      - run:
          name: Install Frontend
          command: npm run frontend:install
      - run:
          name: Build Frontend
          command: npm run frontend:build
      - run:
          name: Deploy Frontend
          environment:
            user_name: hassan
            AWS_ACCESS_KEY_ID: AKIARSR6CT7DDVJXQ7NC
            AWS_SECRET_ACCESS_KEY: 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
          command: npm run frontend:deploy
      - run:
          name: Back-End Install
          command: npm run api:install
      - run:
          name: Build and Archive Backend
          command: |-
            npm run api:build
            npm run archive
      - run:
          name: Deploy Backend
          environment:
            AWS_ACCESS_KEY_ID: AKIARSR6CT7DDVJXQ7NC
            AWS_SECRET_ACCESS_KEY: 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
            AWS_DEFAULT_REGION: us-east-1
          command: npm run api:deploy
            